node {
   def commit_id
   def app
   def port
   stage('step a') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs-v11.10.1') {
       sh 'npm install --only=dev'
       sh 'cd ./basics/ && npm test'
     }
   }
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v1/', 'docker-hub-cred') {
        app = docker.build("syncush/docker-cicd:${commit_id}", './basics').push()
     }
   }
   stage('docker run') {
      sh "docker run --rm -d --name docker_test -p 3000 syncush/docker-cicd:$commit_id"
      sh 'docker stop docker_test'
     }
   }

