version: '3.1'
services:
    jenkins:
        build: ./master
        image: syncush/master-jenkins:latest
        container_name: jenkins
        ports:
            - '8080:8080'
            - '50000:50000'
        networks: 
            - jb
    jenkins-slave:
        build: ./slave
        image: syncush/slave-jenkins:latest
        container_name: jenkins-slave
        restart: always
        environment:
            - 'JENKINS_URL=http://jenkins:8080'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock  # Expose the docker daemon in the container
            - ./volume:/home/jenkins # Avoid mysql volume mount issue
        networks: 
        - jb
        depends_on:
            - jenkins

networks: 
  jb:
